language: go
install:
  - go get -v github.com/spf13/hugo
script:
  - hugo version
  - make build

deploy:
  provider: pages
  skip-cleanup: true
  target-branch: master
  github-token: $GH_TOKEN
  keep-history: true
  verbose: true
  on:
    branch: master
